version: '2.1'

volumes:
  www-data:

services:
  livehelperchat:
    container_name: livehelperchat
    image: victorrds/livehelperchat:fpm
    build: ../fpm/
    volumes:
      - www-data:/var/www/html
    expose:
      - 9000
    links:
      - database
    restart: on-failure
    network_mode: "bridge"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: lhc_db
    hostname: lhc_db
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=livehelperchat
      - MYSQL_PASSWORD=livehelperchat
      - MYSQL_DATABASE=livehelperchat
    expose:
      - 3306
    restart: on-failure
    network_mode: "bridge"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10

  webserver:
    container_name: lhc_httpd
    hostname: lhc_httpd
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    links:
      - livehelperchat
    volumes:
      - www-data:/var/www/html:ro
      - ./livehelperchat.conf:/etc/nginx/conf.d/default.conf
    network_mode: "bridge"
    depends_on:
      - livehelperchat
    restart: on-failure