version: '2.1'

volumes:
  www-data:

services:
  livehelperchat:
    container_name: livehelperchat
    image: victorrds/livehelperchat:fpm
    build: ../fpm/
    volumes:
      - www-data:/var/www/html
      - ./livehelperchat/cache:/var/www/html/cache
      - ./livehelperchat/var:/var/www/html/var
      - ./livehelperchat/settings:/var/www/html/settings
    expose:
      - 9000
    links:
      - database
    restart: on-failure
    network_mode: "bridge"
    depends_on:
       - database
        #condition: service_healthy

  database:
    container_name: database
    hostname: database
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=livehelperchat
      - MYSQL_PASSWORD=livehelperchat
      - MYSQL_DATABASE=livehelperchat
    expose:
      - 3306
    volumes:
      - ./database/data:/var/lib/mysql 
    restart: on-failure
    network_mode: "bridge"
    #healthcheck:
    #  test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #  interval: 20s
    #  timeout: 20s
    #  retries: 10

  webserver:
    container_name: webserver
    hostname: webserver
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    links:
      - livehelperchat
    volumes:
      - www-data:/var/www/html:ro
      - ./webserver/livehelperchat.conf:/etc/nginx/conf.d/default.conf
    network_mode: "bridge"
    depends_on:
      - livehelperchat
    restart: on-failure